name: 'Build Models and Readme'

on: push

jobs:
  build:
    name: Build README and STL meshes
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Create README.md
        run: |
          make readme
      
      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"

          git add README.md
          git commit -am "Build README.md
          
          
          Co-authored-by: Matteo Bnora <bonora.matteo@gmail.com>"

      - name: Export FreeCAD projects
        run: docker run -iv $(pwd):/3d amrit3701/freecad-cli:latest make -C /3d freecad
      
      - name: Commit
        run: |
          git add -f */*.stl

          git commit -m "Build FreeCAD projects
          
          
          Co-authored-by: Matteo Bnora <bonora.matteo@gmail.com>"

      - name: Build SolveSpace Docker image
        run: docker build -t solvespace -f Dockerfile.solvespace .

      - name: Export SolveSpace projects
        run: docker run -iv $(pwd):/3d solvespace

      - name: Commit & Push
        run: |
          git add -f */*.stl

          git commit -m "Build SolveSpace projects
          
          
          Co-authored-by: Matteo Bnora <bonora.matteo@gmail.com>"

          git push