name: 'Build Models and Readme'

on: push

jobs:
  build:
    name: Build STL meshes and upload to Thingiverse
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: recursive

      #- name: Make README.md
      #  continue-on-error: true
      #  run: make readme
      
      #- name: Commit & Push
      #  continue-on-error: true
      #  run: |
      #    git config user.name github-actions
      #    git config user.email github-actions@github.com
      #    git add README.md

      #    git commit -m "Build README.md

      #    
      #    Co-authored-by: Matteo Bonora <bonora.matteo@gmail.com>"

      #    git push

      #- name: Export FreeCAD projects
      #  continue-on-error: true
      #  run: docker run -iv $(pwd):/3d amrit3701/freecad-cli:latest make -C /3d freecad
      #
      #- name: Commit
      #  continue-on-error: true
      #  run: |
      #    git add -f */*.stl
      #    git commit -m "Build FreeCAD projects
      #    
      #    
      #    Co-authored-by: Matteo Bonora <bonora.matteo@gmail.com>"

      #    git push

      #- name: Build SolveSpace Docker image
      #  continue-on-error: true
      #  run: docker build -t solvespace -f .utils/Dockerfile.solvespace .

      #- name: Export SolveSpace projects
      #  continue-on-error: true
      #  run: docker run -iv $(pwd):/3d solvespace

      #- name: Commit & Push
      #  continue-on-error: true
      #  run: |
      #    git add -f */*.stl
      #    git commit -m "Build SolveSpace projects
      #    
      #    
      #    Co-authored-by: Matteo Bonora <bonora.matteo@gmail.com>"

      #    git push
      
      - name: Upload to Thingiverse
        env:
          THINGIVERSE_KEY: ${{ secrets.THINGIVERSE_KEY }}
          THINGIVERSE_SECRET: ${{ secrets.THINGIVERSE_SECRET }}
          THINGIVERSE_TOKEN: ${{ secrets.THINGIVERSE_TOKEN }}
        run: |
          pip install requests requests_toolbelt
          make install-deps
          make upload
